
 services:
  mariadb:
    container_name: inception-mariadb
    build: ./Mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    networks:
      - inception

  wordpress:
    container_name: inception-wordpress
    build: ./Wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"   # WordPress écoute généralement sur 80
    volumes:
      - wordpress_data:/var/www/wordpress


  nginx:
    container_name: inception-nginx
    build: ./Nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "8080:80"
      - "443:443" # SSL si configuré
    volumes:
      - ./Nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Nginx/tools/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./Nginx/tools/localhost.key:/etc/ssl/private/localhost.key:ro

 volumes:
  mariadb_data:
  wordpress_data:

 networks:
  inception:
    driver: bridge


